### ISSUE TITLE
Unzip taking a long time and using a large amount of memory

### ISSUE THREAD

**Issue by katholan** [nadegeguiglielmoni/GraphUnzip#15]
I am trying to run GraphUnzip on a Flye assembly of ONT reads (used --keep-haplotypes flag) of a ~160 Mb genome using HiC reads, but it is taking a very long time and using a lot of memory (my current run is 40 hours at 200 GB of memory). I'm not sure if this is a bug or if I'm doing something wrong.

Contact matrix and fragments list generated with HiCStuff

Interaction Matrix Command
`python3 graphunzip.py HiC-IM -m abs_fragments_contacts_weighted.txt -F fragments_list.txt -g assembly_graph.gfa --HiC_IM interaction_matrix.txt`

It finished in ~3 hours with no errors that I can find. Output:

> Loading the GFA file
> Loading contigs
> Loading links
> Building the interaction matrix
> Exporting Hi-C interaction matrix as  interaction_matrix.txt

Mapped long reads .gaf output from GraphAligner

Unzip Command
`python3 graphunzip.py -g assembly_graph.gfa -i interaction_matrix.txt -l graphaligner.gaf -f output.fasta -o output.gfa unzip`

Output

> Loading the GFA file
> Loading contigs
> Loading links
> Loading the Hi-C interaction matrix
> Everything loaded, moving on to untangling the graph
> Reading the gaf file…
> Finished going through the gaf file.
> Building consensus bridges from all the long reads
> Done building consensus bridges of 1215
> Now we will determine through an iterative process what contigs of the assembly are present only once in the final genome
> Out of 1215 supposed single-copy contigs, 259 were not actually haploid. Recomputing until all the single-copy contigs are robust.
> Let's move on to actually untangling the graph
> Processed 0 contigs out of 2275, while untangling with long reads.

And then it either fails due to not enough memory (over 250 GB) or it times out (over 4 days).

Any insight into this issue would be much appreciated!

**Comment by RolandFaure** [comment]
Hello,
A new version of GraphUnzip was just pushed. It might solve your problems, since the improvements in the algorithms makes them much faster (and more precise). I'd recommend you try again with this version.

However your graph does not look huge (2275 contigs), so GraphUnzip should take at most a few minutes to process it. It might be a bug. If you don't mind me looking at the graph, you can send me your files (without the actual DNA sequences or the CIGARs to make it lighter) at roland.faure@irisa.fr.

- The GFA (without the sequences):
awk '{if (substr($1,1,1)=="S"){print $1 "\t" $2 "\t*";} else {print}}' assembly_graph.gfa > graph_without_sequences.gfa 

- The GAF (without the CIGARs): 
awk -F '\t' '{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6}' graphaligner.gaf > graphaligner_light.gaf

- interactionMatrix.txt

The output of GraphUnzip before it ran out of time looks promising, we'll probably be able to untangle the assembly, at least partially :-)

**Comment by RolandFaure** [comment]
Hi, 
Thank you for sending me your files. I've looked at them. Your GFA is of extraordinary complexity (I'd be curious to know how you obtained such a GFA) : almost all contigs are linked to almost all other contigs ! GraphUnzip got 'lost' trying to navigate through this graph.
I've made a few adaptations to make GraphUnzip suitable for such graphs. Please use the 'dev' branch for now, the changes will be more permanently integrated in the main branch later.

**For very very complex graphs, use --exhaustive option**. GraphUnzip will delete all links it does not find in the gaf file, making the graph accessible.

For your particular case, GraphUnzip now finishes in less than 5 minutes on my laptop (without sequences). The graph is still very complex though, so GraphUnzip improves the contiguity but maybe not as much as you would have dreamt.

Thank you for bringing this issue up, do not hesitate to reopen this issue if you still have trouble running GraphUnzip.
